title: <center><b>Victor Rosales</b></center>

logo: assets/img/photo-github-f2c.png

description: <p><center><b>Egresado de IngenierÃ­a Civil</b></center></p><p align="justify"><center>Top 10% PromociÃ³n 2024-1</center><br><center> <a href="assets/files/CV_2024.pdf">ğŸ“„Resume</a> | <a href="https://www.linkedin.com/in/vadrianrc/">LinkedIn</a> | <a href="https://github.com/vadrianrc">GitHub</a> | <a href="https://www.credly.com/users/victor-adrian-rosales-cutipa">Credly</a></center></p><span><center><b>Contacto</b></center></span><p>TelÃ©fono:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ğŸ“ (+51) 964066333</p>Correo electrÃ³nico:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;âœ‰ï¸ vadrianrosalescutipa@gmail.com<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;âœ‰ï¸ victor.rosales.c@uni.pe

show_downloads: False

theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
