title: <center><b>Victor Rosales</b></center>

logo: /assets/img/photo-github2.png

description: <p><center><b>Estudiante de IngenierÃ­a Civil</b></center></p><p align="justify">Estudiante de dÃ©cimo ciclo de IngenierÃ­a Civil en la Universidad Nacional de IngenierÃ­a con estudios enfocados en la rama de estructuras.<br><center> <a href="assets/files/L1-Infografia.pdf">ğŸ“„Resume</a> | <a href="https://www.linkedin.com/in/vadrianrc/">LinkedIn</a> | <a href="https://github.com/vadrianrc">GitHub</a></center></p><span><center><b>Contacto</b></center></span><p>TelÃ©fono:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ğŸ“ (+51) 964066333</p>Correo electrÃ³nico:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;âœ‰ï¸ vadrianrosalescutipa@gmail.com<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;âœ‰ï¸ victor.rosales.c@uni.pe

show_downloads: False

theme: jekyll-theme-minimal

remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
